### ISSUE TITLE
Add `hal::write_partial(serial&)` + `hal::write(serial&)`

### ISSUE THREAD

**Issue by kammce** [libhal-google/libhal#412]
```C++
result<size_t> hal::write_partial(serial&, span<bytes>)
```

Simply writes to serial port and returns the number of bytes. The number of bytes can be equal to or less than the span of bytes passed to the function. This is akin to simply calling `serial::write` directly.

```C++
status hal::write(serial&, span<bytes>)
```

This is a blocking operation that will write the contents of the byte span in full. To do this, simply call `serial::write` and check how many bytes have been sent. If the span of byte is 10 bytes and only 5 bytes were sent, then this function should send the last 5 bytes to the write function. Repeat this process until all of the bytes have been sent.

**Comment by GregoryAgnew** [comment]
.take
