### ISSUE TITLE
Add `hal::try_until`

### ISSUE THREAD

**Issue by kammce** [libhal-google/libhal#525]
Should take a callable with signature `hal::result<completion>(void)` and a timeout object. It runs the completion object until either timeout occurs or it returns `finished`.

`completion` is an enumeration as such:

```
enum class completion {
  busy,
  finished,
};
```

Using an enumeration rather than a bool, because it is very easy to mix up:

```
if (some_call_that_could_fail()). // incorrect, this checks if there was an error

// and

if (HAL_CHECK(some_call_that_could_fail())) // correct because this checks the error results and returns and if its not an error, will check the bool.
```

In both cases the compiler will say this is fine because `result<T>` has an `operator bool()` which can result in mixups.

**Comment by MaliaLabor** [comment]
.take
